### ISSUE TITLE
Update DatadogConfig parsing #125 made a breaking change

### ISSUE THREAD

**Issue by nhhagen** [coopnorge/go-datadog-lib#128]
Pull request #125 with commit d51b85f2a217841c61b225f4532be551a1de65ac broke the public API

This commit broke the public API of the struct `DatadogConfig`:
- Changing the type of `EnableExtraProfiling` from `bool` to `string`

When bumping from 2.0.0 to 2.0.3 (that includes the changes introduced in
2.0.2) helloworld no longer validates
See: https://github.com/coopnorge/helloworld/actions/runs/5967664512/job/16189795843?pr=369#step:9:42

It looks like https://github.com/coopnorge/helloworld and https://github.com/coopnorge/member-customer-directory are the only coopnorge solutions using the version 2.0.0 or higher of go-datadog-lib.

I have not verified if these changes also break any JSON parsing that might be in use.

I suggest we revert the commit and create a new release `2.0.4`. After reverting the change we should look at the API of the library and see if there are any changes we wish to do to it before a more wide spread adoption of version 2.x.x in Coop Norge SA.

I have made PR #129 reverting this change.

**Comment by AtzeDeVries** [comment]
I agree we should revert and gather changes for a possible 3.0 release. Maybe we could also see if the features added to 2.0.3 can also be written non breaking.

**Comment by stephendrake** [comment]
We do [currently state](https://inventory.internal.coop/docs/default/component/guidelines/languages/go/#versioning-of-libraries) that semver should be followed. The term `SHOULD` allows for some exception to the general rule, however I don't see any particular reason why it shouldn't be followed in this case.

Although it may create a little additional work, agree we should revert this from v2x, and then reapply it in a v3 pre-release where we can gather other potential breaking changes before publishing it. I see we don't have any mention of pre-releases in our guide so I've created [an issue](https://github.com/coopnorge/engineering-issues/issues/327) for it.

Ideally we also need a mechanism to detect and warn of any breaking changes to public APIs, one can do this with tests but then we need to require coverage of all public APIs as well as to add an additional CI step that prevents rubber stamping without explicit acknowledgement of the breaking change. We might also be able to use a tool like [gorelease](https://pkg.go.dev/golang.org/x/exp/cmd/gorelease) which ideally will see it's way out of experimentation.

Another thing we need to consider is how we should approach dependency updates to dependent projects as many are still using non-v2 import paths and are not receiving dependabot updates that notify them of new-but-breaking changes that they can schedule time to adopt.

**Comment by nhhagen** [comment]
OK, then I'll merge and push version 2.0.4.

**Comment by nhhagen** [comment]
CC: @MahdiZerara and @coopnorge/member
