### ISSUE TITLE
Review Notes

### ISSUE THREAD

**Issue by aucampia** [coopnorge/go-datadog-lib#17]
@nhhagen asked me to do a review but the PRs were already merged, so I'm taking notes here:

### Minor: [URL vs URL Reference](https://datatracker.ietf.org/doc/html/rfc3986#appendix-A) vs Path

URLs, and even URL References, are very different from Posix/OS Paths. Paths can contain space characters while URI paths can't, if this is a not a URL it should not have `url` in the variable name:

https://github.com/coopnorge/go-datadog-lib/blob/2e629313203952e41f1b0644099936fa740638b7/config/config.go#L16-L17

### Minor: Consider using https://github.com/go-playground/validator

https://github.com/coopnorge/go-datadog-lib/blob/2e629313203952e41f1b0644099936fa740638b7/config/config.go#L21-L46

### Code generation target for go-mocks

It would be nice if there was a target for generatin mocks with go-mock. It could be incorporated it with the use of [devtools-golang](https://github.com/coopnorge/go-datadog-lib/issues/17)

### Check if `metrics.DatadogMetrics` implements `metrics.DatadogMetricsClient` 

`metrics.DatadogMetrics` is attempting to implement `metrics.DatadogMetricsClient`, it would be good to check if it does so correctly, one way to do it is to add a line like:

```go
var (
	_ DatadogMetricsClient         = (*DatadogMetrics)(nil)
)
```

See this for example: https://github.com/coopnorge/go-masker-lib/blob/321468eb1344c9c13b09688ef6c9695ce5b3da67/censoredstring.go#L38-L43

### minor: is  `metrics.DatadogMetricsClient` adding value?

I'm not sure if this is adding value and it may not be very idiomatic for go to be declaring it if it is not really useful. Do we expect something else from the same library to implement it ever? If not then it may be best to leave it up to clients to decide how to accommodate this.

### `metrics.NewDatadogMetrics` error handling

I'm not too sure if this is ideal:

https://github.com/coopnorge/go-datadog-lib/blob/2e629313203952e41f1b0644099936fa740638b7/metric/datadog.go#L37-L43

I think if you ask a library to do something, and it can't do it, that the library should give an error back to the caller so the caller can handle in. In this case you fall back to doing something other than what the client asked for and then if that fails continue.

I would say it is better to return the error to the caller so they don't end up with broken objects at weird places.

### package `metrics` in directory `metric`

https://github.com/coopnorge/go-datadog-lib/blob/2e629313203952e41f1b0644099936fa740638b7/metric/datadog.go#L1

This violates: https://go.dev/doc/effective_go#package-names

> Another convention is that the package name is the base name of its source directory; the package in src/encoding/base64 is imported as "encoding/base64" but has name base64, not encoding_base64 and not encodingBase64.

### Is it really worth it to allow/ignore `m.c.GetClient() == nil` ?

https://github.com/coopnorge/go-datadog-lib/blob/2e629313203952e41f1b0644099936fa740638b7/metric/metric.go#L55-L57

Would it not be better to return an error for this? If users want to ignore errors it is their choice. Not returning an error makes it impossible for them to make this choice.

Also I think if you propagate errors in `metrics.NewDatadogMetrics`  it may end up better.

### Forces dependency on both echo and grpc

As far as I can tell if I use `middleware` I will get dependency on `google.golang.org/grpc` and `github.com/labstack/echo`. This is not ideal, it would be best if we could find some what to allow users to only use what they need. One option is to put the echo and grpc stuff in seperate packages, e.g.

- https://github.com/coopnorge/go-identity-lib/blob/7ba6a3b940e565b691ea6d41eb92d209ce671c10/echomw/echomw.go
- https://github.com/coopnorge/go-identity-lib/blob/7ba6a3b940e565b691ea6d41eb92d209ce671c10/interceptor/interceptor.go

### non-idomatic package name `go_datadog_lib`

https://github.com/coopnorge/go-datadog-lib/blob/7965e52e4d17dac0949c23c750229ae93570d7bd/bootstrap.go#L1

This does not follow:

https://go.dev/doc/effective_go#package-names

### `go_datadog_lib.StartDatadog` does not propagate errors

https://github.com/coopnorge/go-datadog-lib/blob/7965e52e4d17dac0949c23c750229ae93570d7bd/bootstrap.go#L13-L17

https://github.com/coopnorge/go-datadog-lib/blob/7965e52e4d17dac0949c23c750229ae93570d7bd/bootstrap.go#L48

I would say ideally these errors should propagate to the caller. If they want to ignore them that is their prerogative. 

> By convention, packages are given lower case, single-word names; there should be no need for underscores or mixedCaps. Err on the side of brevity, since everyone using your package will be typing that name.

**Comment by LinMAD** [comment]
@aucampia 
>  // APM Socket path for apm and profiler, unix prefix not needed, example: /var/run/dd/apm.socket 
> APM string `mapstructure:"dd_trace_agent_url"` 

That change will affect agent configuration for all projects in Coop, it's already will be problematic to fix it. So there is low chance to update that globally. Besides it actually could be socket or URL in DD

**Comment by aucampia** [comment]
CC: @nhhagen @LinMAD please have a look.

**Comment by aucampia** [comment]
> 



> That change will affect agent configuration for all projects in Coop, it's already will be problematic to fix it. So there is low chance to update that globally. Besides it actually could be socket or URL in DD

We can make an issue then to fix it later, but if you have a variable name URL and it cannot take a URL or people put non URLs in there you will end up with a bad time. Variable names should not be contradictory.

**Comment by LinMAD** [comment]
Ok, it's hard to replay each block so I'll do it by comments sections - easier to replay.

> ![image](https://user-images.githubusercontent.com/13393702/203017155-7df8bcde-e73c-4624-9a6c-6efba196f213.png)
Someone needs to take that to the cloud platform if these changes must be done. For now, it's out of the scope of this repository. @nhhagen can make a note about that for cloud platform guild day.

**Comment by LinMAD** [comment]
> ![image](https://user-images.githubusercontent.com/13393702/203017611-7d8155fd-bb3c-448d-8975-50d1008e4941.png)

@aucampia 
Not convinced, for consumers must have fewer dependencies for the package it's better. 

Besides consumers can decide to use their own validation or not, the same as implementing their own bootstrap or configuration.

**Comment by aucampia** [comment]
> Besides consumers can decide to use their own validation or not, the same as implementing their own bootstrap or configuration.

It would not be visible to consumers, it would be in your code where you would call this instead of hand writing validation for it. But fair enough, may not be worth it.

**Comment by LinMAD** [comment]
> ![image](https://user-images.githubusercontent.com/13393702/203018167-da85c272-4be8-4570-9e5f-88ad710ad5fc.png)

@aucampia  It's internal code, which is a point to verify if the package implements its own interface, looks more redundant. Can you provide expanded details why?

**Comment by LinMAD** [comment]
> > 
> 
> > That change will affect agent configuration for all projects in Coop, it's already will be problematic to fix it. So there is low chance to update that globally. Besides it actually could be socket or URL in DD
> 
> We can make an issue then to fix it later, but if you have a variable name URL and it cannot take a URL or people put non URLs in there you will end up with a bad time. Variable names should not be contradictory.

@aucampia  Yeah, it's used only for one place, and dragging the whole library to check 3-4 fields looks overkill.

**Comment by LinMAD** [comment]
> ![image](https://user-images.githubusercontent.com/13393702/203018789-c54e97b5-2b34-4f18-9bd3-141c790ec0e8.png)

@aucampia Yes, you can implement `DatadogMetricsClient` with your own metrics that are coupled with domain logic. Like we had that in an internal project to aggregate and send cart value. So `DatadogMetricsClient` only provides access to Datadog StatsD - how the consumer will use it it's up to the developer, if `BaseMetricCollector` is enough then ok, if it requires more domain logic - easily can be inherited from `DatadogMetricsClient`.

**Comment by aucampia** [comment]
> @aucampia It's internal code, which is a point to verify if the package implements its own interface, looks more redundant. Can you provide expanded details why?

If it is internal code should it not go into `internal/...` ? But regardless, either the interface is not needed (which if it is internal, and the symbol is not referenced at all in this code base, which it is not, then it is not needed), or it is is needed, and then it is good to ensure that you implement it correctly so that someone does not inadvertently change the code in a way that no longer implements it without noticing.

**Comment by LinMAD** [comment]
> ![image](https://user-images.githubusercontent.com/13393702/203019593-8d7d2b67-a6d9-4636-82e1-07dfc500396e.png)

@aucampia  Yep, in case if consumer didn't used pkg `DatadogMetricsClient ` or didn't used constructor, maybe it was disabled at all but code for metrics still in place so it's not throwing nullptr and panic crash

**Comment by LinMAD** [comment]
> > @aucampia It's internal code, which is a point to verify if the package implements its own interface, looks more redundant. Can you provide expanded details why?
> 
> If it is internal code should it not go into `internal/...` ? But regardless, either the interface is not needed (which if it is internal, and the symbol is not referenced at all in this code base, which it is not, then it is not needed), or it is is needed, and then it is good to ensure that you implement it correctly so that someone does not inadvertently change the code in a way that no longer implements it without noticing.

@aucampia Mixing meaning, internall in a way for Datadog not like internal for package - it just provides a pure connection and all API for Datadog as an instance.

**Comment by aucampia** [comment]
> > ![image](https://user-images.githubusercontent.com/13393702/203019593-8d7d2b67-a6d9-4636-82e1-07dfc500396e.png)
> 
> @aucampia Yep, in case if consumer didn't used pkg `DatadogMetricsClient ` or didn't used constructor, maybe it was disabled at all but code for metrics still in place so it's not throwing nullptr and panic crash

So why not return an error and let the caller decide what to do about it, what good it is it to make it a no-op? If they did not use `DatadogMetricsClient` then they should not be calling this as it does nothing. There are many ways to use standard go library that will also result in panic crashes, we can't save users from making panic crashes, but silently ignoring failures is also not great. To me either someone should correctly construct this or they should not call this.

**Comment by LinMAD** [comment]
> ![image](https://user-images.githubusercontent.com/13393702/203020287-f0a2fb07-24f4-4531-b8a1-43b40eb3d7b7.png)

@aucampia is not a dependency at all, consumer can use native middleware from Datadog or implement their own, pckg just provides simple middleware to create nesting spans. In other words, pckg will work without this middleware but then you will do your own work.

**Comment by aucampia** [comment]
> > ![image](https://user-images.githubusercontent.com/13393702/203020287-f0a2fb07-24f4-4531-b8a1-43b40eb3d7b7.png)
> 
> @aucampia is not a dependency at all, consumer can use native middleware from Datadog or implement their own, pckg just provides simple middleware to create nesting spans. In other words, pckg will work without this middleware but then you will do your own work.

If in my code I use `github.com/coopnorge/go-datadog-lib/middleware` then my code will depend on `google.golang.org/grpc` and `github.com/labstack/echo`.

**Comment by LinMAD** [comment]
> > > ![image](https://user-images.githubusercontent.com/13393702/203019593-8d7d2b67-a6d9-4636-82e1-07dfc500396e.png)
> > 
> > 
> > @aucampia Yep, in case if consumer didn't used pkg `DatadogMetricsClient ` or didn't used constructor, maybe it was disabled at all but code for metrics still in place so it's not throwing nullptr and panic crash
> 
> So why not return an error and let the caller decide what to do about it, what good it is it to make it a no-op? If they did not use `DatadogMetricsClient` then they should not be calling this as it does nothing. There are many ways to use standard go library that will also result in panic crashes, we can't save users from making panic crashes, but silently ignoring failures is also not great. To me either someone should correctly construct this or they should not call this.

@aucampia depends on how you look at that, if it's like debug and you just disabled transport then it will be ignored for that configuration. If your metrics do extra profiling as an example and for a specific environment you could just add transport.
The same idea as for slices, for you loop you would provide an empty slice just to not add extra handling since it's the default value.
You can check Robert C. Martin - Clean Code ideas it's more expanded there.

**Comment by LinMAD** [comment]
> > > ![image](https://user-images.githubusercontent.com/13393702/203020287-f0a2fb07-24f4-4531-b8a1-43b40eb3d7b7.png)
> > 
> > 
> > @aucampia is not a dependency at all, consumer can use native middleware from Datadog or implement their own, pckg just provides simple middleware to create nesting spans. In other words, pckg will work without this middleware but then you will do your own work.
> 
> If in my code I use `github.com/coopnorge/go-datadog-lib/middleware` then my code will depend on `google.golang.org/grpc` and `github.com/labstack/echo`. At least as far as I can tell, if this is not the case can you explain why it is not the case?

No, your code will just use `grpc` then, and go mods will not add echo to your project.

**Comment by aucampia** [comment]
> No, your code will just use `grpc` then, and go mods will not add echo to your project.

This is not accurate I think, have a look at this: https://github.com/aucampia/examples/tree/01a28f1d626822011181ffa4cf10a463f4b7ea0f/coopnorge-go-datadog-lib

It only uses `middleware.TraceUnaryServerInterceptor()`  but echo ends up in `go.mod` and in the binary.

**Comment by LinMAD** [comment]
> > No, your code will just use `grpc` then, and go mods will not add echo to your project.
> 
> This is not accurate I think, have a look at this: https://github.com/aucampia/examples/tree/01a28f1d626822011181ffa4cf10a463f4b7ea0f/coopnorge-go-datadog-lib
> 
> It only uses `middleware.TraceUnaryServerInterceptor()` but echo ends up in `go.mod` and in the binary.

Interesting, for example in other project, ppl use `https://github.com/DataDog/dd-trace-go` then we end up the same here, so it still looks like overkill to split it app into 3 reps.

**Comment by aucampia** [comment]
> > > No, your code will just use `grpc` then, and go mods will not add echo to your project.
> > 
> > 
> > This is not accurate I think, have a look at this: https://github.com/aucampia/examples/tree/01a28f1d626822011181ffa4cf10a463f4b7ea0f/coopnorge-go-datadog-lib
> > It only uses `middleware.TraceUnaryServerInterceptor()` but echo ends up in `go.mod` and in the binary.
> 
> @aucampia Interesting, for example in other project, ppl use `https://github.com/DataDog/dd-trace-go` then we end up the same here, so it still looks like overkill to split it app into 3 reps.

I don't mean to suggest split it into three repos, I think just having it in 2 packages in the same repo should be fine. I will make an example when I have time.

**Comment by aucampia** [comment]
> > ![image](https://user-images.githubusercontent.com/13393702/203018789-c54e97b5-2b34-4f18-9bd3-141c790ec0e8.png)
> 
> @aucampia Yes, you can implement `DatadogMetricsClient` with your own metrics that are coupled with domain logic. Like we had that in an internal project to aggregate and send cart value. So `DatadogMetricsClient` only provides access to Datadog StatsD - how the consumer will use it it's up to the developer, if `BaseMetricCollector` is enough then ok, if it requires more domain logic - easily can be inherited from `DatadogMetricsClient`.

I'm fine with keeping it, as it does not hurt, but I'm still unclear if it helps, and it is not idiomatic. For more info see:

https://github.com/golang/go/wiki/CodeReviewComments#interfaces

> Go interfaces generally belong in the package that consumes values of the interface type, not a package that implements the interface type.

**Comment by aucampia** [comment]
> @aucampia depends on how you look at that, if it's like debug and you just disabled transport then it will be ignored for that configuration. If your metrics do extra profiling as an example and for a specific environment you could just add transport.

As far as I can tell (I may be wrong), the only way to get `metrics.DatadogMetricsClient` that returns nil is:

1. Cause  `metrics.NewDatadogMetrics` to fail, which will log an error.
2. Implement `metrics.DatadogMetricsClient` yourself.

I agree that sometimes you don't want to run without metrics for local debugging and we should accommodate it, but when you do so option 2 is not ideal and 1 is not ideal either. The best solution is to explicitly have a way to disable reporting (without also creating an error condition) by either providing a flag to disable it or by making the URL optional.

If the code is changed to have a way to create `metrics.DatadogMetricsClient` with a `nil` client that does not result in an error then I would be fine with this:

https://github.com/coopnorge/go-datadog-lib/blob/7965e52e4d17dac0949c23c750229ae93570d7bd/metric/metric.go#L55-L57

**Comment by LinMAD** [comment]
> > @aucampia depends on how you look at that, if it's like debug and you just disabled transport then it will be ignored for that configuration. If your metrics do extra profiling as an example and for a specific environment you could just add transport.
> 
> As far as I can tell (I may be wrong), the only way to get `metrics.DatadogMetricsClient` that returns nil is:
> 
> 1. Cause  `metrics.NewDatadogMetrics` to fail, which will log an error.
> 2. Implement `metrics.DatadogMetricsClient` yourself.
> 
> I agree that sometimes you don't want to run without metrics for local debugging and we should accommodate it, but when you do so option 2 is not ideal and 1 is not ideal either. The best solution is to explicitly have a way to disable reporting (without also creating an error condition) by either providing a flag to disable it or by making the URL optional.
> 
> If the code is changed to have a way to create `metrics.DatadogMetricsClient` with a `nil` client that does not result in an error then I would be fine with this:
> 
> https://github.com/coopnorge/go-datadog-lib/blob/7965e52e4d17dac0949c23c750229ae93570d7bd/metric/metric.go#L55-L57

@aucampia Yes it's a different way of doing but I don't wanna break Open/closed principle, once again if consumers don't wanna use `BaseMetricCollector` they can create their own since it follows Interface segregation and  Dependency injection.

**Comment by LinMAD** [comment]
@aucampia Overall it seems like we speaking about similar things but from different angles, the output of the discussion leads to the same principles at the end with the same value but just with some diffs. So I don't see much value here to continue playing with facts since time-wise it's not valuable. If you have a contract contribution suggestion or open PR then we will look at the case.

**Comment by aucampia** [comment]
> @aucampia Yes it's a different way of doing but I don't wanna break Open/closed principle

How is this breaking the open/closed principle?

> The best solution is to explicitly have a way to disable reporting (without also creating an error condition) by either providing a flag to disable it or by making the URL optional.

**Comment by aucampia** [comment]
> @aucampia Overall it seems like we speaking about similar things but from different angles, the output of the discussion leads to the same principles at the end with the same value but just with some diffs. So I don't see much value here to continue playing with facts since time-wise it's not valuable.

Failure to propagate errors and bad package naming is not just a matter of opinion. But okay, I will make separate issues for those.

**Comment by aucampia** [comment]
> > @aucampia Overall it seems like we speaking about similar things but from different angles, the output of the discussion leads to the same principles at the end with the same value but just with some diffs. So I don't see much value here to continue playing with facts since time-wise it's not valuable.
> 
> Failure to propagate errors and bad package naming is not just a matter of opinion. But okay, I will make separate issues for those.


Closing this as I created separate issues:

- https://github.com/coopnorge/go-datadog-lib/issues/24
- https://github.com/coopnorge/go-datadog-lib/issues/23
- https://github.com/coopnorge/go-datadog-lib/issues/22
- https://github.com/coopnorge/go-datadog-lib/issues/21
- https://github.com/coopnorge/go-datadog-lib/issues/20
- https://github.com/coopnorge/go-datadog-lib/issues/25

**Comment by LinMAD** [comment]
> > > @aucampia Overall it seems like we speaking about similar things but from different angles, the output of the discussion leads to the same principles at the end with the same value but just with some diffs. So I don't see much value here to continue playing with facts since time-wise it's not valuable.
> > 
> > 
> > Failure to propagate errors and bad package naming is not just a matter of opinion. But okay, I will make separate issues for those.
> 
> Closing this as I created separate issues:
> 
> * [add code generation targets for mocks #24](https://github.com/coopnorge/go-datadog-lib/issues/24)
> * [misleading config variable names #23](https://github.com/coopnorge/go-datadog-lib/issues/23)
> * [package `metrics` in directory `metric` #22](https://github.com/coopnorge/go-datadog-lib/issues/22)
> * [The base package name is not idomatic #21](https://github.com/coopnorge/go-datadog-lib/issues/21)
> * [`metrics.NewDatadogMetrics` does not propagate errors #20](https://github.com/coopnorge/go-datadog-lib/issues/20)
> * [`go_datadog_lib.StartDatadog` does not propagate errors #25](https://github.com/coopnorge/go-datadog-lib/issues/25)

@aucampia You cannot just ignore the previous conversation and create issue because you think your way is the only way...
