### ISSUE TITLE
Maybe make tracing wrapper function not return error??

### ISSUE THREAD

**Issue by pwmb** [coopnorge/go-datadog-lib#182]
https://github.com/coopnorge/go-datadog-lib/blob/e89d0730826c897a72cc0138d819cc9c3521c506/tracing/tracing.go#L22

We should't return error here but `NoopSpan` so that the consumer don't need to check `if err != nil { ... }` all the time.  

Datadog already have the same implemented as well

https://github.com/DataDog/dd-trace-go/blob/5e9b0b1fb7ff458c744c66211ba8cf11b901c100/ddtrace/internal/globaltracer.go#L69

**Comment by bendiknesbo** [comment]
Even though such a change would not be a breaking API signature change, there might be some code relying on the fact that it actually returns an error, so we would have to feature-flag it if we want to return NoopSpan, or we could create a new function that does not return err.

At the other hand, I am pushing for a bigger rewrite of this lib (v3), that should iron out a lot of the pains of using it today.

**Comment by arunpoudel** [comment]
@bendiknesbo I will disagree. It will be a breaking change, as the function signature will change. We might have to introduce another function and keep the old one as well.

**Comment by bendiknesbo** [comment]
Depends on how you do it.
```go
func CreateNestedTrace(sourceCtx context.Context, operation, resource string) (ddtrace.Span, error) {
	span := getSpanFromContext(sourceCtx)
	if span == nil {
		if featureFlag {
    		    return noopSpan{}, nil // new
    		}
		return nil, fmt.Errorf("inheritance failed, parent span tracer not found in context") // old
	}

	nestedSpan := tracer.StartSpan(operation, tracer.ResourceName(resource), tracer.ChildOf(span.Context()))

	return nestedSpan, nil
}
```

If we do it like this, then users of the lib can call `nestedSpan, _ := tracing.CreateNestedTrace(...)` after setting the feature flag, until we release a v3.

**Comment by nhhagen** [comment]
We could for now introduce a new function and in a second PR mark the old one as deprepacted. This will prompt people to use the new way instead of the old way.

We can use this method to redesign most the lib.

Following what is described here: https://zchee.github.io/golang-wiki/Deprecated/ (I cannot speak to the quality of this source of information).
