### ISSUE TITLE
Config validation SHOULD return ValidationError(s)

### ISSUE THREAD

**Issue by arunpoudel** [coopnorge/go-datadog-lib#188]
Right now we only have one method to validate datadog config.

```
IsDataDogConfigValid() bool
```

which only returns a boolean when something is wrong. When using this to migrate old project to new library, I had to dig into the lib code, to understand what keys were missing.

My suggestion is implement:

```
Validate() (bool, error)
```

Which returns a set of validation error that are present in the datadog config.

**Comment by arunpoudel** [comment]
Maybe the implementation SHOULD use https://github.com/hashicorp/go-multierror to return multiple errors.

**Comment by nhhagen** [comment]
This sounds like something we should implement. After releasing this function we should deprecate the old one in a later release.
