### ISSUE TITLE
grpc example references echo

### ISSUE THREAD

**Issue by aucampia** [coopnorge/go-datadog-lib#19]
https://github.com/coopnorge/go-datadog-lib/blob/7965e52e4d17dac0949c23c750229ae93570d7bd/docs/1%20-%20Setup/README.md?plain=1#L146

**Comment by aucampia** [comment]
For more context see: 

https://github.com/coopnorge/go-datadog-lib/blob/7965e52e4d17dac0949c23c750229ae93570d7bd/docs/1%20-%20Setup/README.md#L128-L163

More specifically from this section, which is about gRPC:

https://github.com/coopnorge/go-datadog-lib/blob/7965e52e4d17dac0949c23c750229ae93570d7bd/docs/1%20-%20Setup/README.md#L141-L147

Which is the line I referenced when opening it:

https://github.com/coopnorge/go-datadog-lib/blob/7965e52e4d17dac0949c23c750229ae93570d7bd/docs/1%20-%20Setup/README.md?plain=1#L146

**Comment by LinMAD** [comment]
Was decoupled to sub-packages -> https://github.com/coopnorge/go-datadog-lib/tree/main/middleware
