### ISSUE TITLE
misleading config variable names

### ISSUE THREAD

**Issue by aucampia** [coopnorge/go-datadog-lib#23]
URLs, and even URL References, are very different from Posix/OS Paths. Paths can contain space characters while URI paths can't, if this is a not a URL it should not have `url` in the variable name:

https://github.com/coopnorge/go-datadog-lib/blob/2e629313203952e41f1b0644099936fa740638b7/config/config.go#L16-L17

**Comment by aucampia** [comment]
For previous discussion:

- https://github.com/coopnorge/go-datadog-lib/issues/17

**Comment by LinMAD** [comment]
@aucampia That request affects general configuration inside Coop, this repository is just affected by this setup but in the scope of pckg not belong to that refactor. Consumers of pkg can re-implement the configuration.

Move this issue where the cloud platform configured Agent for Datadog otherwise it can be closed.

**Comment by nhhagen** [comment]
Where is the documentation on the platform side. I could not find it in the Observability platform onboarding guide: https://inventory.internal.coop/docs/default/component/coop-playbook/platforms/cloud_platform/observability/guide_how_to_onboard_datadog/

As @aucampia states the config variable name is miss leading, the issue should stay open in this library even if the library is the cause.

@coopnorge/cloud-platform do you know anything about `dd_trace_agent_url`?

**Comment by LinMAD** [comment]
@nhhagen https://inventory.internal.coop/docs/default/component/coop-playbook/platforms/cloud_platform/observability/guide_how_to_onboard_datadog/#endpoints-for-metrics-and-traces

**Comment by nhhagen** [comment]
`DD_TRACE_AGENT_URL` is originates from `gopkg.in/DataDog/dd-trace-go.v1` and required to be set for proper operations.
