### ISSUE TITLE
Add support for checking if Datadog integration is enabled

### ISSUE THREAD

**Issue by nhhagen** [coopnorge/go-datadog-lib#306]
## Context

The current implementation is most services today is to assume that a miss configured Datadog integration should be disabled. This works fine in local development environment, but causes issues in production like environments when the Datadog configuration is bad. With a bad configuration the service will start as normal, but no APM data or traces will be sendt. This is an implicit behaviour and it does not help our engineers.

## Proposal

Implement an environment variable that if set to `false` disables the Datadog integration. If the environment variable is not set it should be assumed to be `true`.

`isEnabled()` can be implemented inside of `StartDatadog()` so that no code changes are required by consuming services.

If `isEnabled()` returns `true` we call `config.Validate()`, if there is a configuration error we return that and do not start Datadog.

This will allow us to remove Datadog configuration validation from services leaving less boilerplate code.

**Comment by bendiknesbo** [comment]
I agree with the proposal.

Discussion: How should the middleware interact with such an enabling/disabling?
1. Return a no-op middleware (e.g. no-op gRPC interceptor, or just return the original http.Client)
2. Always return a valid middleware/interceptor, and leave the enabled-checking to the caller.

I propose we go with option 1

**Comment by nhhagen** [comment]
@bendiknesbo I think a no-op on disabled, but fails on bad config for midlewares/interceptors as well.

I do not think service implementors should have to explicitly check if a config is valid or not. Keeping it an option as we have today is fine (for now).
