### ISSUE TITLE
Improved setup/start/bootstrap and teardown/shutdown functions

### ISSUE THREAD

**Issue by nhhagen** [coopnorge/go-datadog-lib#427]
`coopdatadog.StartDatadog(cfg config.DatadogParameters, connectionType ConnectionType) error` and `coopdatadog.GracefulDatadogShutdown()`has several issues that requires addressing.

1. The function pair are not designed in a way that is idiomatic to go. A function that is paired with a teardown/shutdown requirement should return a `context.CancelFunc` this allow us to use guardrails like linters to catch if the teardown/shutdown function is not called.
2. The startup function is not context aware, this again triggers more cognitive load on users to ensure that shutdown is called in a situation where a parent context is canceled.
3. An interface is used for providing the configuration for Datadog, this can cause issues when adding new  optional configuration parameters. Consumer of the library that has created their own struct implementing the configuration interface are forced implement support for optional configuration that is not relevant for their context.
4. We allow for programatic configuration of Datadog options that must be configured using official environment variables that `ddtrace-go` relies on.
5. Metrics collection is not  initialised

To improve this I suggest that we create a new setup/bootstrap function that is context aware, take functional options for parameters that are safe to set programatically and returns a `context.CancelFunc`. If we can avoid implementing any functional options that is potentially ideal, but to avoid breaking changes in the future the parameter should be in place.

Here is an example, for discussion purposes, leading with the usage. The context awareness might not be correctly implemented, but should show the intent.

```go
package main

import (
	"github.com/coopnorge/go-logger"
	"github.com/coopnorge/go-datadog-lib/v2"
	signals "github.com/coopnorge/go-signal-lib"
)

func main() {
	err := run()
	if err != nil {
		logger.WithError(err).Fatal("Unexpected error")
	}
}

func run() error {
	ctx, cancel := signals.HandleSignals(context.Background())
	defer cancel()

	ctx, cancel, err = datadog.Start(ctx)
	defer cancel()
	if err != nil {
		return err
	}

	err = runServer()

	if err != nil && !signals.IsSignalErr(ctx) {
		return err
	}
	return nil
}
```

```go
package coopdatadog

// Start the Datadog integration, use the returned context.CancelFunc to stop
// the Datadog integration.
func Start(ctx context.Context, options ...Option) (context.Context, context.CancelFunc, error) {
	config := &Config{
		shutdownTimeout: 5 * time.Second,
	}

	for _, option := range options {
		option(config)
	}

	ctx, cancel := context.WithCancel(ctx)
	canceldd := context.CancelFunc(func() {
		stop(config)
		cancel()
	})

	err := start(ctx, config)
	return ctx, canceldd, err
}

// Config is the internal configuration for the Datadog integration
type Config struct {}

// Option is the function signature for Datadog integration configuration
// options
type Option func(*Config)

// start all relevant collectors, tracing, metrics, profiling etc
func start(ctx context.Context, config *Config) error {
...
}

// stop with a graceful shutdown that includes flushing signals.
func stop(config *Config) {
...
}
```

**Comment by bendiknesbo** [comment]
This looks good, and we can then ensure that we start everything we need.

I would recommend settings the config in 3 parts:
1. Setting some sane defaults
2. Overriding from environment variables
3. Overriding from functional options

**Comment by hadrienk** [comment]
Good plan Niels.

In addition to the Start() method you are planing, maybe we can have separate Start() methods in `trace`/`profiler`/`metric` package that only start part of the dd systems? 

Regarding the environment vs. options, I think this is a very common pitfall and I generally like to either panic or return an error if there's any ambiguity (as opposed to overriding). I find that failing fast in those cases is better.

**Comment by hawi74** [comment]
LGTM, although I am not sure if `Start()` should wrap & return new context. Conceptually this means that the rest of the application will be a child of datadog, but IMO datadog should be treated as a sidecar. Of course the current proposal does not enforce it (the user can decide to ignore the returned context), but encourages it.

```golang
package main

func run() error {
	ctx, cancel := signals.HandleSignals(context.Background())
	defer cancel()

	// the library will attempt to gracefully shut down when ctx is cancelled
	err = datadog.Start(ctx)
	if err != nil {
		return err
	}

	err = runServer(ctx)

	if err != nil && !signals.IsSignalErr(ctx) {
		return err
	}
	return nil
}
```

```golang
package coopdatadog

func Start(ctx context.Context, options ...Option) (context.Context, context.CancelFunc, error) {
	config := &Config{
		shutdownTimeout: 5 * time.Second,
	}

	for _, option := range options {
		option(config)
	}

	ctx, cancel := context.WithCancel(ctx)
	canceldd := context.CancelFunc(func() {
		stop(config)
		cancel()
	})

	err := start(ctx, config)
    go func() {
		<-ctx.Done()
        stop(config)
    }()
	return err
}
```

**Comment by bendiknesbo** [comment]
> LGTM, although I am not sure if `Start()` should wrap & return new context. Conceptually this means that the rest of the application will be a child of datadog, but IMO datadog should be treated as a sidecar. Of course the current proposal does not enforce it (the user can decide to ignore the returned context), but encourages it. My proposal:

If we go this route, I would future-proof it by accepting a `context.CancelFunc` that can be called if Datadog crashes (after it has started), so that the entire application will not run indefinitely, thinking it is being actively monitored. I'm not sure if this is something that the current Datadog-library supports, but it definitely wouldn't hurt.

**Comment by bendiknesbo** [comment]
> In addition to the Start() method you are planing, maybe we can have separate Start() methods in `trace`/`profiler`/`metric` package that only start part of the dd systems?

I would recommend against this, and instead let the consumer disable the starting of the different parts with env-vars/func-opts, so that all the consumers can rely on a single entrypoint, and keep the bootstrapping-code as slim as possible on the consumer-side.

**Comment by nhhagen** [comment]
Awesome, thx for the feedback, I think I have enough to start a PR. I'll start it as a draft, feel free to provide input and feedback along the way
